package enumtype.firstenum;

public enum Football {

    GOAL_KEEPER, CENTER_BACK, RIGHT_BACK, RIGHT_WINGER_BACK,
    LEFT_BACK, LEFT_WINGER_BACK, CENTER_DEFENDING_MIDFIELDER,
    MIDFIELDER, RIGHT_MIDFIELDER, LEFT_MIDFIELDER,
    LEFT_CENTER_MIDFIELDER, RIGHT_CENTER_MIDFIELDER,
    CENTER_ATTACKING_MIDFIELDER, RIGHT_WINGER, LEFT_WINGER,
    CENTER_FORWARD, RIGHT_FORWARD, LEFT_FORWARD, STRIKER
}
